//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cvAssemblyOrdersUnlinked
    {
        public Nullable<int> Session { get; set; }
        public Nullable<int> TransactionNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Reference { get; set; }
        public string Document { get; set; }
        public Nullable<int> DocumentNum { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string AODescription { get; set; }
        public string DocumentType { get; set; }
        public string ProductionWorkflowStatus { get; set; }
        public Nullable<decimal> AOQuantity { get; set; }
        public string FProductID { get; set; }
        public string FProductType { get; set; }
        public string FProductRowType { get; set; }
        public string FProductCategory { get; set; }
        public string FProductSalesCategory { get; set; }
        public string AlternateProductID { get; set; }
        public string UPC { get; set; }
        public string FProductDescription { get; set; }
        public string LotNumber { get; set; }
        public string WarehouseID { get; set; }
        public string WarehouseName { get; set; }
        public bool PostedToGL { get; set; }
        public bool PostedToINV { get; set; }
        public int parent { get; set; }
        public int NumSiblings { get; set; }
        public Nullable<int> NumTransactions { get; set; }
        public string CompanyName { get; set; }
    }
}
