//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cvINVTransactionDetailCrystalControl
    {
        public System.Guid GUIDINVTransactionDetail { get; set; }
        public int PKIDINVTransactionDetail { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public Nullable<int> TransactionNumber { get; set; }
        public string TransactionType { get; set; }
        public string PONumber { get; set; }
        public Nullable<System.Guid> GUIDProduct { get; set; }
        public string ProductID { get; set; }
        public string VendorProductID { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> GUIDINVLotSerial { get; set; }
        public Nullable<decimal> QuantityOrdered { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> ComponentQuantity { get; set; }
        public Nullable<decimal> AssemblyComponentQuantity { get; set; }
        public Nullable<decimal> AssemblyQuantity { get; set; }
        public Nullable<decimal> QuantityRejected { get; set; }
        public string Unit { get; set; }
        public string DisplayUnit { get; set; }
        public Nullable<decimal> DisplayUnitFactor { get; set; }
        public Nullable<decimal> ValueDiscrepancy { get; set; }
        public Nullable<decimal> UnitCost { get; set; }
        public string CostUnit { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> FreezeCount { get; set; }
        public Nullable<decimal> PhysicalCount { get; set; }
        public Nullable<int> CountLineNumber { get; set; }
        public string Location { get; set; }
        public string ToLocation { get; set; }
        public Nullable<System.Guid> GUIDWHLocation { get; set; }
        public Nullable<System.Guid> GUIDToWHLocation { get; set; }
        public bool PostedToINV { get; set; }
        public bool PostedToAP { get; set; }
        public bool PostedToGL { get; set; }
        public string Note { get; set; }
        public Nullable<int> InvoiceLineNumber { get; set; }
        public string InvoiceNumber { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<System.Guid> GUIDWarehouse { get; set; }
        public Nullable<int> CostLayer { get; set; }
        public Nullable<System.DateTime> PostedTimestamp { get; set; }
        public Nullable<int> TransactionLine { get; set; }
        public Nullable<int> GLTransactionBatch { get; set; }
        public Nullable<int> TransactionPeriod { get; set; }
        public Nullable<int> TransactionYear { get; set; }
        public Nullable<int> GLTransactionLine { get; set; }
        public Nullable<decimal> AmountPostedToGL { get; set; }
        public Nullable<System.Guid> GUIDJournal { get; set; }
        public Nullable<System.Guid> GUIDDebitAccount { get; set; }
        public Nullable<System.Guid> GUIDCreditAccount { get; set; }
        public Nullable<System.Guid> GUIDInvoiceDetail { get; set; }
        public Nullable<System.Guid> GUIDOrderDetailLot { get; set; }
        public Nullable<System.Guid> GUIDPODetail { get; set; }
        public bool PriorPeriodAdjustment { get; set; }
        public string FromCostMethod { get; set; }
        public string ToCostMethod { get; set; }
        public bool DoNotSync { get; set; }
        public Nullable<System.Guid> GUIDTaxCode { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<System.Guid> GUIDLayerBatch { get; set; }
        public Nullable<System.Guid> GUIDAssociatedITD { get; set; }
        public string FProductCategory { get; set; }
        public Nullable<bool> VariableQuantity { get; set; }
        public byte[] FSignature { get; set; }
        public Nullable<int> Sequence { get; set; }
    }
}
