//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CerinimbusDevEntities : DbContext
    {
        public CerinimbusDevEntities()
            : base("name=CerinimbusDevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cvAssemblyOrdersUnlinked> cvAssemblyOrdersUnlinkeds { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<ProductAltID> ProductAltIDs { get; set; }
        public virtual DbSet<tbAccess> tbAccesses { get; set; }
        public virtual DbSet<tbAccessPermission> tbAccessPermissions { get; set; }
        public virtual DbSet<tbAccessPermissionGroup> tbAccessPermissionGroups { get; set; }
        public virtual DbSet<tbAccessPermissionMaster> tbAccessPermissionMasters { get; set; }
        public virtual DbSet<tbCustomDataList> tbCustomDataLists { get; set; }
        public virtual DbSet<tbCustomField> tbCustomFields { get; set; }
        public virtual DbSet<tbDocument> tbDocuments { get; set; }
        public virtual DbSet<tbEmployee> tbEmployees { get; set; }
        public virtual DbSet<tbINVLotSerial> tbINVLotSerials { get; set; }
        public virtual DbSet<tbINVRegister> tbINVRegisters { get; set; }
        public virtual DbSet<tbINVTransaction> tbINVTransactions { get; set; }
        public virtual DbSet<tbINVTransactionDetail> tbINVTransactionDetails { get; set; }
        public virtual DbSet<cvINVTransactionDetailCrystalControl> cvINVTransactionDetailCrystalControls { get; set; }
        public virtual DbSet<tbNumber> tbNumbers { get; set; }
        public virtual DbSet<tbProduct> tbProducts { get; set; }
        public virtual DbSet<tbProductClass> tbProductClasses { get; set; }
        public virtual DbSet<tbProductComponent> tbProductComponents { get; set; }
        public virtual DbSet<tbProductControlType> tbProductControlTypes { get; set; }
        public virtual DbSet<tbProductCostMethod> tbProductCostMethods { get; set; }
        public virtual DbSet<tbProductionWorkflowStatu> tbProductionWorkflowStatus { get; set; }
        public virtual DbSet<tbProductSalesCategory> tbProductSalesCategories { get; set; }
        public virtual DbSet<tbProductType> tbProductTypes { get; set; }
        public virtual DbSet<tbProductUnit> tbProductUnits { get; set; }
        public virtual DbSet<tbSalespersonInfo> tbSalespersonInfoes { get; set; }
        public virtual DbSet<tbSystem> tbSystems { get; set; }
        public virtual DbSet<tbSystemOption> tbSystemOptions { get; set; }
        public virtual DbSet<tbWarehouse> tbWarehouses { get; set; }
        public virtual DbSet<tbWHLocation> tbWHLocations { get; set; }
        public virtual DbSet<tbWorkFlowStatu> tbWorkFlowStatus { get; set; }
    }
}
