//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAltID
    {
        public System.Guid GUIDProduct { get; set; }
        public string ProductID { get; set; }
        public string AlternateProductID { get; set; }
        public string Description { get; set; }
        public string UPC { get; set; }
    }
}
