//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAccess
    {
        public System.Guid GUIDAccess { get; set; }
        public string ID { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string EMail { get; set; }
        public string EmailSignature { get; set; }
        public string BCCAddress { get; set; }
        public string MessageAddr { get; set; }
        public bool Active { get; set; }
        public Nullable<System.Guid> GUIDSalesperson { get; set; }
        public bool AutoOpenAlerts { get; set; }
        public bool AutoOpenActivities { get; set; }
        public bool AutoOpenSchedule { get; set; }
        public string DefaultActivityType { get; set; }
        public string DefaultScheduleClass { get; set; }
        public bool AutoOpenDashboard { get; set; }
        public bool AutoOpenOrderManager { get; set; }
        public bool RestrictBySalesperson { get; set; }
        public bool EmailSettingsOverride { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<int> EmailType { get; set; }
        public int SMTPEncryption { get; set; }
        public bool SMTPAuthRequired { get; set; }
    }
}
