//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCustomField
    {
        public System.Guid GUIDCustomField { get; set; }
        public string TableID { get; set; }
        public string TableName { get; set; }
        public int Sequence { get; set; }
        public string Label { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string Extra { get; set; }
    }
}
