//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDocument
    {
        public System.Guid GUIDDocument { get; set; }
        public Nullable<System.Guid> GUIDLink { get; set; }
        public string LinkType { get; set; }
        public string FileName { get; set; }
        public string FileExtension { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string AddedBy { get; set; }
        public byte[] DocumentData { get; set; }
    }
}
