//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbEmployee
    {
        public System.Guid GUIDEmployee { get; set; }
        public string EmployeeListID { get; set; }
        public string EmployeeId { get; set; }
        public string PayrollEmployeeID { get; set; }
        public Nullable<decimal> CostRate { get; set; }
        public Nullable<decimal> BillingRate { get; set; }
        public string LaborRate { get; set; }
        public string Salutation { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string HomePhoneNum { get; set; }
        public string EmergPhoneNum { get; set; }
        public string EMail { get; set; }
        public string JobTitle { get; set; }
        public string DepartmentID { get; set; }
        public string LocationID { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
