//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbINVRegister
    {
        public int PKIDINVRegister { get; set; }
        public System.Guid GUIDINVRegister { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Source { get; set; }
        public string OpenedBy { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public bool PostedToINV { get; set; }
        public string PostedToINVBy { get; set; }
        public Nullable<System.DateTime> DatePostedToINV { get; set; }
        public bool PostedToGL { get; set; }
        public string PostedToGLBy { get; set; }
        public Nullable<System.DateTime> DatePostedToGL { get; set; }
        public bool PostedToAP { get; set; }
        public string PostedToAPBy { get; set; }
        public Nullable<System.DateTime> DatePostedToAP { get; set; }
        public string Note { get; set; }
        public Nullable<int> GLTransactionBatch { get; set; }
        public Nullable<short> TransactionPeriod { get; set; }
        public Nullable<short> TransactionYear { get; set; }
        public Nullable<int> ParentRegNumber { get; set; }
        public Nullable<System.Guid> GUIDLandedCostPODetail { get; set; }
        public Nullable<System.DateTime> VoidedDate { get; set; }
        public string VoidedBy { get; set; }
        public Nullable<System.Guid> GUIDOrder { get; set; }
    }
}
