//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbINVLotSerial
    {
        public System.Guid GUIDINVLotSerial { get; set; }
        public System.Guid GUIDProduct { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string Reference { get; set; }
        public string Location { get; set; }
        public string Specification { get; set; }
    }
}
