//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbINVTransaction
    {
        public int PKIDINVTransaction { get; set; }
        public System.Guid GUIDINVTransaction { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public Nullable<int> TransactionNumber { get; set; }
        public Nullable<System.Guid> GUIDWarehouse { get; set; }
        public Nullable<System.Guid> GUIDToWarehouse { get; set; }
        public string DocumentType { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public string AssemblyType { get; set; }
        public string VendorInvoiceID { get; set; }
        public Nullable<int> GLTransactionNumber { get; set; }
        public Nullable<System.Guid> GUIDGLInventoryAccount { get; set; }
        public Nullable<System.Guid> GUIDGLOffsetAccount { get; set; }
        public bool PostedToGL { get; set; }
        public bool PostedToAP { get; set; }
        public bool PostedToINV { get; set; }
        public Nullable<System.Guid> GUIDVendor { get; set; }
        public string VendorName { get; set; }
        public string PONumber { get; set; }
        public decimal ExchangeRate { get; set; }
        public string Reference { get; set; }
        public string Document { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public Nullable<int> TransactionPeriod { get; set; }
        public Nullable<System.Guid> GUIDProductionWorkflowStatus { get; set; }
        public bool TaxIncluded { get; set; }
        public bool BeginningOfDay { get; set; }
        public Nullable<decimal> InvoiceAmount { get; set; }
        public Nullable<decimal> SalesTax { get; set; }
        public Nullable<System.Guid> GUIDInProgressUser { get; set; }
        public Nullable<System.DateTime> InProgressDate { get; set; }
        public Nullable<System.Guid> GUIDOrderDetail { get; set; }
    }
}
