//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNumber
    {
        public string NumberType { get; set; }
        public Nullable<int> NextNumber { get; set; }
        public Nullable<int> LowNumber { get; set; }
        public Nullable<int> HighNumber { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
        public bool NoWrap { get; set; }
    }
}
