//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public string ProductID { get; set; }
        public bool Taxable { get; set; }
        public Nullable<System.Guid> SalesGUIDTaxCode { get; set; }
        public Nullable<System.Guid> PurchaseGUIDTaxCode { get; set; }
        public bool TaxByCategory { get; set; }
        public Nullable<System.Guid> GUIDTaxCategory { get; set; }
        public bool TaxInPrice { get; set; }
        public bool AllowOverride { get; set; }
        public bool AllowZero { get; set; }
        public Nullable<short> CommissionType { get; set; }
        public Nullable<decimal> CommPct { get; set; }
        public Nullable<decimal> CommAmt { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Length { get; set; }
        public bool VariableWeight { get; set; }
        public bool VariableLength { get; set; }
        public string Specification { get; set; }
        public string ProductPriceCategory { get; set; }
        public bool PriceByCategory { get; set; }
        public Nullable<System.Guid> GUIDProductClass { get; set; }
        public Nullable<int> LeadTime { get; set; }
        public string SalesCategory { get; set; }
        public bool Discontinued { get; set; }
        public string CostMethod { get; set; }
        public string ProductType { get; set; }
        public string InventoryControlType { get; set; }
        public string AssemblyType { get; set; }
        public string CountCycle { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool Status { get; set; }
        public string Note { get; set; }
        public bool Popup { get; set; }
        public string PONote { get; set; }
        public bool POPopup { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string Size { get; set; }
        public bool VariableHeight { get; set; }
        public bool VariableVolume { get; set; }
        public bool VariableWidth { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string TechSpec { get; set; }
        public string WebAddress { get; set; }
        public string AltDescription { get; set; }
        public string Description { get; set; }
        public System.Guid GUIDProduct { get; set; }
        public bool NotForResale { get; set; }
        public int MaintainInventoryType { get; set; }
        public bool AvailOnWeb { get; set; }
        public byte[] ProductPicture { get; set; }
        public bool ShipCompleteLots { get; set; }
        public Nullable<decimal> AltWeight { get; set; }
        public Nullable<decimal> AltLength { get; set; }
        public Nullable<decimal> AltHeight { get; set; }
        public Nullable<decimal> AltWidth { get; set; }
        public Nullable<decimal> AltVolume { get; set; }
        public Nullable<decimal> AltUnitsPerPalletLayer { get; set; }
        public Nullable<decimal> PalletLayers { get; set; }
        public Nullable<decimal> InnerPackQty { get; set; }
        public Nullable<decimal> OuterPackQty { get; set; }
        public bool Discountable { get; set; }
        public string SalesUnit { get; set; }
        public string PurchaseUnit { get; set; }
        public string PackageUnit { get; set; }
        public Nullable<decimal> LandedCostFactor { get; set; }
        public string C_ControlGroup { get; set; }
        public string C_ControlDataType { get; set; }
        public string C_ControlMethod { get; set; }
        public string C_ControlSpec { get; set; }
        public Nullable<decimal> C_ControlMin { get; set; }
        public Nullable<decimal> C_ControlMax { get; set; }
    }
}
