//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductComponent
    {
        public System.Guid GUIDProductComponent { get; set; }
        public System.Guid GUIDProduct { get; set; }
        public string ComponentType { get; set; }
        public System.Guid ComponentGUIDProduct { get; set; }
        public Nullable<System.Guid> GUIDComponentWarehouse { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public bool VariableQuantity { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Note { get; set; }
    }
}
