//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductCostMethod
    {
        public string CostMethod { get; set; }
        public string Description { get; set; }
        public bool LotSerialNumbered { get; set; }
        public bool Standard { get; set; }
        public bool Active { get; set; }
    }
}
