//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductUnit
    {
        public string BaseUnit { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public string FactorBasis { get; set; }
        public bool Active { get; set; }
        public bool Discrete { get; set; }
    }
}
