//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductSalesCategory
    {
        public bool Active { get; set; }
        public string Description { get; set; }
        public string SalesCategory { get; set; }
        public Nullable<System.Guid> GUIDSalesAccount { get; set; }
        public Nullable<System.Guid> GUIDReturnsAccount { get; set; }
        public Nullable<System.Guid> GUIDTradeDiscount { get; set; }
        public Nullable<System.Guid> GUIDCOGSAccount { get; set; }
        public Nullable<System.Guid> GUIDClass { get; set; }
    }
}
