//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSalespersonInfo
    {
        public System.Guid GUIDSalesperson { get; set; }
        public string SalespersonListID { get; set; }
        public string SalespersonID { get; set; }
        public string Name { get; set; }
        public string LinkType { get; set; }
        public Nullable<System.Guid> GUIDLink { get; set; }
        public Nullable<System.Guid> GUIDSalesAccount { get; set; }
        public Nullable<System.Guid> GUIDReturnsAccount { get; set; }
        public Nullable<System.Guid> GUIDTradeDiscount { get; set; }
        public Nullable<System.Guid> GUIDCOGSAccount { get; set; }
        public Nullable<System.Guid> GUIDClass { get; set; }
        public bool Status { get; set; }
        public Nullable<System.DateTime> TimeCreated { get; set; }
        public Nullable<System.DateTime> TimeModified { get; set; }
    }
}
