//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbSystem
    {
        public System.Guid GUID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Country { get; set; }
        public string WebAddress { get; set; }
        public string EMail { get; set; }
        public string Phone { get; set; }
        public string FAX { get; set; }
        public string DBVersion { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string EIN { get; set; }
        public string SSN { get; set; }
        public Nullable<int> FirstMonthFiscalYear { get; set; }
        public byte[] Logo { get; set; }
        public string SMTPServer { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<int> EmailType { get; set; }
        public int SMTPEncryption { get; set; }
        public bool SMTPAuthRequired { get; set; }
        public string QBMSConnectionTicket { get; set; }
        public string QuickBooksCountry { get; set; }
        public Nullable<System.DateTime> DemoBaseDate { get; set; }
        public Nullable<System.DateTime> MetricsLastSentDate { get; set; }
        public Nullable<System.Guid> GUIDHomeCurrency { get; set; }
        public string GUIHexColor { get; set; }
    }
}
