//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalSystemAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbWarehouse
    {
        public System.Guid GUIDWarehouse { get; set; }
        public string WarehouseID { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> AssociatedGUIDBranch { get; set; }
        public Nullable<System.Guid> GUIDInventoryAccount { get; set; }
        public Nullable<System.Guid> GUIDPurchaseAccount { get; set; }
        public Nullable<System.Guid> GUIDAdjustmentAccount { get; set; }
        public Nullable<System.Guid> GUIDAssemblyLaborAccount { get; set; }
        public Nullable<System.Guid> GUIDAssemblyOtherCostAccount { get; set; }
        public Nullable<System.Guid> GUIDIssueAccount { get; set; }
        public Nullable<System.Guid> GUIDNonInvOffsetAccount { get; set; }
        public Nullable<System.Guid> GUIDLaborOffsetAccount { get; set; }
        public Nullable<System.Guid> GUIDOtherChargeOffsetAccount { get; set; }
        public Nullable<System.Guid> GUIDShippingOffsetAccount { get; set; }
        public Nullable<System.Guid> GUIDLandedCostOffsetAccount { get; set; }
        public string Name { get; set; }
        public string ShipToAttentionOf { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string EMail { get; set; }
        public string ShipVia { get; set; }
        public string FOB { get; set; }
        public bool MaintainInventory { get; set; }
        public Nullable<decimal> LaborCost { get; set; }
        public bool Active { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string FAX { get; set; }
        public string Phone { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<System.Guid> GUIDGainLossAccount { get; set; }
        public Nullable<System.Guid> GUIDPartner { get; set; }
    }
}
